web: 
  image: e1ee1e11/gogs:0.8.10
  links: 
    - mysql 
  ports: 
    - "3000:3000" 
    - "3001:22" 
 
mysql: 
  image: mysql:5.7 
  environment: 
    - MYSQL_ROOT_PASSWORD=gogs 
    - MYSQL_DATABASE=gogs 
