db:
  image: e1ee1e11/postgresql_armhf:9.4.8-1
  environment:
    - POSTGRES_USER=openerp_8
    - POSTGRES_PASSWORD=qwerty

web:
  image: dmisdani/arm-odoo:8.0
  links:
    - db:db
  volumes:
    - /home/ubuntu/odoo_addons:/opt/openerp_8/my_addons
  ports:
    - "18069:8069"
